### ISSUE TITLE
The keyboard shortcut allowing to open the console of the web browser is wrong in the tutorial "Let's get started with Maven and Bck2Brwsr VM"

### ISSUE THREAD

**Issue by gouessej** [jtulach/bck2brwsr#12]
Hello

You wrote 

> While in browser console (press F12 to open it)

[here](https://github.com/jtulach/bck2brwsr/blob/master/docs/MAVEN.md) whereas it's not the correct keyboard shortcut in Mozilla Firefox as you can see in [its list of keyboard shortcuts](https://developer.mozilla.org/en-US/docs/Tools/Keyboard_shortcuts). Actually, it opens the developer tools and selects the most recently used tab in Mozilla Firefox. Personally, I would rewrite the sentence to tell that F12 opens the developer tools and then you have to select the right tab to show the console as there is no way of opening the web console with exactly the same keyboard shortcut on all web browsers (Microsoft Edge uses Control + 2 where Mozilla Firefox uses Control + Shift + K).

**Comment by jtulach** [comment]
Thanks for your interest in Bck2Brwsr I've updated documentation as you suggested.
