### ISSUE TITLE
Passing byte array to javascript

### ISSUE THREAD

**Issue by norzak** [jtulach/bck2brwsr#15]
I didnt check how the byte array is generated(Int8Array?) by the transpiler but, Is it possible to pass a byte array to javascript by reference (such as Int8Array) ?

**Comment by jtulach** [comment]
Hi. Thanks for your interest in [bck2brwsr](http://bck2brwsr.apidesign.org)!

Java `byte[]` array is just a JavaScript `Array` filled with small numbers. It is left up to the JavaScript JIT compiler to optimize that into something more efficient. The standard way to pass objects between Java and JavaScript is to use [Apache HTML/Java API](http://bits.netbeans.org/html+java/1.6.1/net/java/html/js/package-summary.html) that explicitly requires copy on transfer semantics for arrays (see section _Arrays by Copy_) as that is the only behavior portable between [various platforms](https://github.com/dukescript/dukescript-presenters/blob/master/README.md).

If you need call by reference, then there is Bck2Brwsr's own [@JavaScriptBody annotation](http://hudson.apidesign.org/job/bck2brwsr.javadoc/lastSuccessfulBuild/artifact/rt/core/target/site/apidocs/index.html) which passes all arguments (including arrays) by reference. That annotation isn't portable and only works in Bck2Brwsr.

Alternatively, you can instantiate `Int8Array` in JavaScript (e.g. method annotated by `@JavaScriptBody`) and access its elements directly. If you don't want to write the JavaScript yourself, there is a [generated wrapper](https://dukescript.com/javadoc/libs/net/java/html/lib/Int8Array.html) which you can try to use.

I hope you succeed in whatever you are doing with Bck2Brwsr VM!
