### ISSUE TITLE
Allow threads to start (without guarantees when)

### ISSUE THREAD

**Issue by johanvos** [jtulach/bck2brwsr#32]
Although there are no guarantees that Thread.start() should start immediately, it would be useful if the method is at least implemented (not throwing a SecurityException).
I realize this might create false promises, with developers expecting their code to be executed "within a reasonable time" and if their current thread is never released, the new Thread won't start. However, in many cases with short-lived threads, it's perfectly ok.

**Comment by jtulach** [comment]
I don't think it makes sense to support `Thread.start()` without support for `Object.wait()` and `Object.notify()`. While declaring all functions as `async function` would be a way to achieve that, I don't have any plans to do that for Bck2Brwsr right now.That'd be quite complex rewrite.

However PR #33 suggests a way for you to replace `Thread.start()` with your own implementation if you really want to do it.
