### ISSUE TITLE
JavaScriptBody on constructor not working

### ISSUE THREAD

**Issue by marciodel** [jtulach/bck2brwsr#4]
Hi,
  I'm trying to put a `@net.java.html.js.JavaScriptBody` in a constructor but it generates wrong code.
  Is it supported?
Thanks!

**Comment by jtulach** [comment]
Honestly, this hasn't come to my mind! Obviously you can workaround it by:
```java
class A {
  A() {
    I init0();
  }
  @JavaScriptBody(...)
  private native void init0();
```
I hope that's going to be enough for now.

**Comment by marciodel** [comment]
This is how I've been implementing. Yes, it's enough. 
I've just created the issue because @JavaScriptBody has CONSTRUCTOR as target.

Thanks!

**Comment by jtulach** [comment]
Best solution is to remove the ability to apply the annotation to constructors. That will be done in future version of HTML/Java API. Bck2Brwsr's proprietary `@org.apidesign.bck2brwsr.core.JavaScriptBody` annotation will continue to support constructors.
