### ISSUE TITLE
Elemental2 porting

### ISSUE THREAD

**Issue by marciodel** [jtulach/bck2brwsr#5]
Hi,
 
   I'm trying to convert Elemental2 to Bck2Brwsr to provide a migration path from GWT, but I'm not able to compile an initial test. 

   I've attached the source code adapted from the bck2brwser archetype. Do you think I'm am in the correct path?

Thanks!

[xjsi.zip](https://github.com/jtulach/bck2brwsr/files/1025652/xjsi.zip)

**Comment by jtulach** [comment]
@monacotoni has a nice example: https://github.com/dukescript/dukescript-canvas/blob/master/canvas-api/src/main/java/com/dukescript/impl/canvas/HTML5GraphicsEnvironment.java

Having a way to easily migrate from GWT would be great!

**Comment by jtulach** [comment]
Had you had any progress porting Elemental2 or any other related activity?

**Comment by marciodel** [comment]
HI @jtulach , sorry for the long delay. I moved to Dublin and a new job. I didn't had time to progress in this project. But as soon as possible I'll finish it.
