### ISSUE TITLE
insecure websocket 

### ISSUE THREAD

**Issue by johanvos** [jtulach/bck2brwsr#50]
When running a transpiled app locally, everything works fine. 
When running on a remote webserver, I get following fatal error:
Mixed Content: The page at 'https://abc.de/web/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://download2.gluonhq.com/heartbeat'. This request has been blocked; this endpoint must be available over WSS.

This seems to be introduced with c1fb56626452592d2a7d6fb9d43cc284b17a0419

**Comment by johanvos** [comment]
changing            
` var s = new WebSocket('ws://' + location.host + '/heartbeat');
`          
into 

`  var s = new WebSocket('wss://' + location.host + '/heartbeat');
`
works, but that might not work on all browsers?

**Comment by jtulach** [comment]
Would using [0.53](http://wiki.apidesign.org/wiki/Bck2Brwsr_0.53) version
help?

čt 30. 9. 2021 v 12:41 odesílatel Johan Vos ***@***.***>
napsal:

**Comment by johanvos** [comment]
Yes, that helps. Sorry, I missed that later commit. Works fine now!
