### ISSUE TITLE
Is there any option to have a single Javascript file [QUESTION]

### ISSUE THREAD

**Issue by norzak** [jtulach/bck2brwsr#6]
Is there an option to merge bck2brwsr.js with the produced code into a single javascript file?

**Comment by jtulach** [comment]
Yes, that is definitely possible. The default *one .js per one .jar* style was built upon the original transpiler that generated just a single `.js` file. If you control your compiler manually, then see [this Javadoc](http://hudson.apidesign.org/job/bck2brwsr.javadoc/lastSuccessfulBuild/artifact/rt/vm/target/site/apidocs/index.html) - unless you specify `Bck2Brwsr.library(true)`, you'll generate a self contained single `.js` file for all specified classes. As usual, the best is to see some tests. For example [TestVM.java](https://github.com/jtulach/bck2brwsr/blob/master/rt/vm/src/test/java/org/apidesign/vm4brwsr/TestVM.java) is using the compilation to single `.js` file.

**Comment by norzak** [comment]
Thank you very much for the directions, I will try this.

**Comment by norzak** [comment]
One more think to clear up; What happens to the following invokation code when we merge bck2brwsr.js with appclass.js into a single js file.
        
var vm = bck2brwsr('appclass.js');
var c = vm.loadClass('com.x.client.system.Task');
c.invoke('main');

I presume like this

var vm = bck2brwsr();
var c = vm.loadClass('com.x.client.system.Task');
c.invoke('main');

Is this correct?

**Comment by norzak** [comment]
Also from what I understand, there is no command line interface for the bck2brwsr. Basically, I have to write one myself, right?

**Comment by norzak** [comment]
Never mind javadoc explains it all. I was in rush. thanks.
